<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// Initialize Genesis.


//* Grid Style Content Archive 
// function be_archive_post_class( $classes ) {
// 	// Don't run on single posts or pages
// 	if( !is_home() ) 
// 	return $classes;
// 	$classes[] = 'one-third';
// 	global $wp_query;
// 	if( 0 == $wp_query->current_post || 0 == $wp_query->current_post % 3 )
// 	$classes[] = 'first';
// 	return $classes;
//    }
//    add_filter( 'post_class', 'be_archive_post_class' );  
   


//    //* Customize read more text
// add_filter( 'excerpt_more', 'genesis_read_more_link' );
// add_filter( 'get_the_content_more_link', 'genesis_read_more_link' );
// add_filter( 'the_content_more_link', 'genesis_read_more_link' );
// function genesis_read_more_link() {

// 	return '<a class="more-link" href="' . get_permalink() . '"> Read More</a>';

// }
genesis();

?>