<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Header
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */






add_action( 'genesis_header', 'genesis_do_header1' );
/**
 * Echo the default header, including the #title-area div, along with #title and #description, as well as the .widget-area.
 *
 * Does the `genesis_site_title`, `genesis_site_description` and `genesis_header_right` actions.
 *
 * @since 1.0.2
 *
 * @global $wp_registered_sidebars Holds all of the registered sidebars.
 */
function genesis_do_header1() {

	global $wp_registered_sidebars;


	if( get_theme_mod( 'header_position' ) == 'default' )
	{
		
		function nav_right_add_class( $attributes ) {
			$attributes['class'] = $attributes['class']. ' nav-left';
			return $attributes;
			}
			add_filter( 'genesis_attr_nav-primary', 'nav_right_add_class' );
			
		echo "<div class='logo-left'>";
		genesis_markup(
			array(
				'open'    => '<div %s>',
				'context' => 'title-area',
			)
		);
	
	
	
			/**
			 * Fires inside the title area, before the site description hook.
			 *
			 * @since 2.6.0
			 */
	
			do_action( 'genesis_site_title' );
	
			/**
			 * Fires inside the title area, after the site title hook.
			 *
			 * @since 1.0.0
			 */
			do_action( 'genesis_site_description' );
	
	
	
		genesis_markup(
			array(
				'close'   => '</div>',
				'context' => 'title-area',
			)
		);
		echo "</div>";
	}
	
	if( get_theme_mod( 'header_position' ) == 'nav-center' )
	{
		function nav_center_add_class( $attributes ) {
			$attributes['class'] = $attributes['class']. ' nav-center';
			return $attributes;
			}
			add_filter( 'genesis_attr_nav-primary', 'nav_center_add_class' );
			
		echo "<div class='logo-center'>";
		genesis_markup(
			array(
				'open'    => '<div %s>',
				'context' => 'title-area',
			)
		);
	
	
	
			/**
			 * Fires inside the title area, before the site description hook.
			 *
			 * @since 2.6.0
			 */
	
			do_action( 'genesis_site_title' );
	
			/**
			 * Fires inside the title area, after the site title hook.
			 *
			 * @since 1.0.0
			 */
			do_action( 'genesis_site_description' );
	
	
	
		genesis_markup(
			array(
				'close'   => '</div>',
				'context' => 'title-area',
			)
		);
		echo "</div>";
	}
	
	if( get_theme_mod( 'header_position' ) == 'nav-right' )
	{

		function nav_right_add_class( $attributes ) {
			$attributes['class'] = $attributes['class']. ' nav-right';
			return $attributes;
			}
			add_filter( 'genesis_attr_nav-primary', 'nav_right_add_class' );

		echo "<div class='logo-right aabb'>";
		genesis_markup(
			array(
				'open'    => '<div %s>',
				'context' => 'title-area',
			)
		);
	
	
	
			/**
			 * Fires inside the title area, before the site description hook.
			 *
			 * @since 2.6.0
			 */
	
			do_action( 'genesis_site_title' );
	
			/**
			 * Fires inside the title area, after the site title hook.
			 *
			 * @since 1.0.0
			 */
			do_action( 'genesis_site_description' );
	
	
	
		genesis_markup(
			array(
				'close'   => '</div>',
				'context' => 'title-area',
			)
		);
		echo "</div>";
	}
	


	if ( has_action( 'genesis_header_right' ) || ( isset( $wp_registered_sidebars['header-right'] ) && is_active_sidebar( 'header-right' ) ) ) {

		genesis_markup(
			array(
				'open'    => '<div %s>',
				'context' => 'header-widget-area',
			)
		);

			/**
			 * Fires inside the header widget area wrapping markup, before the Header Right widget area.
			 *
			 * @since 1.5.0
			 */
			do_action( 'genesis_header_right' );
			add_filter( 'wp_nav_menu_args', 'genesis_header_menu_args' );
			add_filter( 'wp_nav_menu', 'genesis_header_menu_wrap' );
			dynamic_sidebar( 'header-right' );
			add_filter( 'wp_nav_menu_args', 'genesis_header_menu_args' );
			add_filter( 'wp_nav_menu', 'genesis_header_menu_wrap' );

		genesis_markup(
			array(
				'close'   => '</div>',
				'context' => 'header-widget-area',
			)
		);

	}

}

